#!/bin/bash

echo "🚀 Photo Booth API Comprehensive Test Suite"
echo "=========================================="
echo ""

# Test 1: Direct Model Approach (Working)
echo "📋 Test 1: Direct DynamoDB Model Approach"
echo "----------------------------------------"
node test-direct-model.js
echo ""

# Test 2: Custom Function Approach (Currently failing)
echo "📋 Test 2: Custom Function Approach"
echo "----------------------------------"
node test-api.js
echo ""

# Test 3: Postman-style Test
echo "📋 Test 3: Postman-style Manual Test"
echo "-----------------------------------"
echo "Use these variables in Postman:"
echo ""
echo "GraphQL Query:"
echo "mutation CreateOrder(\$input: CreateOrderInput!) {"
echo "  createOrder(input: \$input) {"
echo "    id"
echo "    customerEmail"
echo "    type"
echo "    status"
echo "    totalPrice"
echo "    currency"
echo "    imageCount"
echo "    images"
echo "    userDetails"
echo "    metadata"
echo "    errorMessage"
echo "    expiresAt"
echo "    createdAt"
echo "    updatedAt"
echo "  }"
echo "}"
echo ""
echo "Variables (Album Order):"
echo "{"
echo "  \"input\": {"
echo "    \"customerEmail\": \"john.doe@example.com\","
echo "    \"type\": \"album\","
echo "    \"status\": \"PENDING\","
echo "    \"totalPrice\": 5.0,"
echo "    \"currency\": \"USD\","
echo "    \"imageCount\": 1,"
echo "    \"images\": \"[\\\"550e8400-e29b-41d4-a716-446655440000\\\"]\","
echo "    \"userDetails\": \"{\\\"name\\\":\\\"John Doe\\\",\\\"email\\\":\\\"john.doe@example.com\\\",\\\"phone\\\":\\\"+1234567890\\\",\\\"address\\\":\\\"123 Main Street\\\",\\\"city\\\":\\\"New York\\\",\\\"postalCode\\\":\\\"10001\\\"}\""
echo "  }"
echo "}"
echo ""
echo "Variables (Collage Order):"
echo "{"
echo "  \"input\": {"
echo "    \"customerEmail\": \"jane.smith@example.com\","
echo "    \"type\": \"collage\","
echo "    \"status\": \"PENDING\","
echo "    \"totalPrice\": 3.0,"
echo "    \"currency\": \"USD\","
echo "    \"imageCount\": 1,"
echo "    \"images\": \"[\\\"6ba7b810-9dad-11d1-80b4-00c04fd430c8\\\"]\","
echo "    \"userDetails\": \"{\\\"name\\\":\\\"Jane Smith\\\",\\\"email\\\":\\\"jane.smith@example.com\\\",\\\"phone\\\":\\\"+1987654321\\\",\\\"address\\\":\\\"456 Oak Avenue\\\",\\\"city\\\":\\\"Los Angeles\\\",\\\"postalCode\\\":\\\"90210\\\"}\""
echo "  }"
echo "}"
echo ""

echo "✅ Test suite completed!"
echo ""
echo "📊 Summary:"
echo "  - Direct Model API: ✅ Working"
echo "  - Custom Function API: ❌ Needs deployment fix"
echo "  - Manual Testing: ✅ Ready for Postman"
